name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Copy buildozer.spec
      run: |
        # Copy your buildozer.spec into the container
        cat > buildozer.spec <<EOL
[app]
title = TikTokReportBot
package.name = tiktokreportbot
package.domain = org.tiktokreport
source.dir = .
source.include_exts = py
source.main = tiktok_report_bot.py
version = 1.0

requirements = python3, kivy==2.3.0, requests

android.minapi = 21
android.api = 33
orientation = portrait
android.permissions = INTERNET
EOL
        
    - name: Build APK
      run: |
        # Install dependencies
        pip install requests
        
        # Build the APK
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
