version: 1.0
buildozer:
  android:
    requirements:
      - python3
      - kivy
      - requests
      - urllib3
      - chardet
      - idna
    permissions:
      - INTERNET
    presplash: null
    icon: null
    orientation: portrait
    fullscreen: 0
    arch: armeabi-v7a
    p4a_branch: master
    p4a_fork: kivy
    bootstrap: sdl2
