name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf automake libtool
        pip install buildozer cython==0.29.36
        
    - name: Patch libffi build
      run: |
        # Apply workaround for autoconf issues
        find ~/.buildozer -name 'configure.ac' -exec sed -i 's/AC_TRY_LINK/AC_LINK_IFELSE/g' {} +
        find ~/.buildozer -name 'configure' -exec sed -i 's/LT_SYS_SYMBOL_USCORE/_LT_SYS_SYMBOL_USCORE/g' {} +
        
    - name: Set environment variables
      run: |
        echo "USE_SDK_WRAPPER=1" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.1.8937393" >> $GITHUB_ENV
        
    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
