name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-distutils
        pip install buildozer cython==0.29.36
        
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec <<EOL
[app]
title = TikTokReportBot
package.name = tiktokreportbot
package.domain = org.tiktokreport
source.dir = .
source.include_exts = py
source.main = tiktok_report_bot.py
version = 1.0

requirements = python3, kivy==2.3.0, requests

android.minapi = 21
android.api = 33
orientation = portrait
android.permissions = INTERNET
EOL
        
    - name: Install Android SDK components
      run: |
        # Create directories
        mkdir -p ~/.android/licenses
        mkdir -p .buildozer/android/platform
        
        # Accept all Android licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ~/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
        
        # Download and install Android SDK
        SDK_URL="https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
        curl -o sdk-tools.zip $SDK_URL
        unzip -q sdk-tools.zip -d android-sdk
        rm sdk-tools.zip
        
        # Set environment variables
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
        
        # Install required components
        yes | sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-33"
        
    - name: Download Android NDK
      run: |
        NDK_URL="https://dl.google.com/android/repository/android-ndk-r25b-linux.zip"
        curl -o ndk.zip $NDK_URL
        unzip -q ndk.zip
        rm ndk.zip
        echo "NDK_PATH=$PWD/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Build APK
      run: |
        # Set environment variables
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export ANDROID_NDK_HOME=$NDK_PATH
        
        # Verify tools
        echo "AIDL path:"
        find $ANDROID_SDK_ROOT -name aidl
        
        # Build the APK
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
