name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk
        pip install buildozer
    - run: buildozer -v android debug
    - uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
