name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk
        pip install buildozer cython==0.29.36
        
    - name: Initialize Buildozer
      run: |
        # Create necessary directories
        mkdir -p .buildozer/android/platform
        # Run a dummy command to initialize environment
        buildozer android -- version || true
        
    - name: Build APK
      run: |
        # Build without cleaning
        buildozer -v android debug \
          -- \
          --p4a-branch=master \
          --ndk-version=25.1.8937393 \
          --sdk-version=33
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
