name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk
          pip install buildozer cython==0.29.36

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and Install Android SDK Command Line Tools
        run: |
          SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip"
          SDK_DIR="${HOME}/android-sdk"
          mkdir -p "${SDK_DIR}"
          curl -o "${SDK_DIR}/commandlinetools.zip" "${SDK_TOOLS_URL}"
          unzip -q "${SDK_DIR}/commandlinetools.zip" -d "${SDK_DIR}/cmdline-tools"
          mv "${SDK_DIR}/cmdline-tools/cmdline-tools" "${SDK_DIR}/cmdline-tools/latest"
          echo "ANDROID_HOME=${SDK_DIR}" >> $GITHUB_ENV
          echo "PATH=$PATH:${SDK_DIR}/cmdline-tools/latest/bin:${SDK_DIR}/platform-tools" >> $GITHUB_ENV

      - name: Accept Android licenses and Install Build Tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platforms;android-30" "platform-tools"

      - name: Configure Buildozer SDK path
        run: |
          # Buildozer expects SDK in ~/.buildozer/android/platform/android-sdk
          # We need to ensure the structure matches what buildozer expects
          mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
          # Create a symlink for sdkmanager to the expected location
          ln -s ${HOME}/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager || true
          # Also symlink the main SDK directory if it doesn't exist already
          ln -s ${HOME}/android-sdk ~/.buildozer/android/platform/android-sdk || true

      - name: Initialize Buildozer
        run: |
          buildozer android --version || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-bot-apk
          path: bin/*.apk
