name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-distutils
        pip install buildozer cython==0.29.36 setuptools
        
    - name: Initialize Buildozer (download SDK)
      run: |
        mkdir -p .buildozer/android/platform
        buildozer android -- version || true
        
    - name: Setup Android SDK and accept licenses
      run: |
        # Set paths
        ANDROID_SDK_ROOT="$PWD/.buildozer/android/platform/android-sdk"
        SDK_MANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
        
        # Create license files
        mkdir -p "$ANDROID_SDK_ROOT/licenses"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK_ROOT/licenses/android-sdk-preview-license"
        
        # Install command-line tools if not present
        if [ ! -f "$SDK_MANAGER" ]; then
          echo "Installing command-line tools..."
          CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
          curl -o cmdline-tools.zip $CMDLINE_TOOLS_URL
          unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          rm cmdline-tools.zip
        fi
        
        # Install required components
        export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        
        yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "build-tools;36.0.0"
        
    - name: Build APK
      run: |
        buildozer -v android debug \
          -- \
          --p4a-branch=master \
          --ndk-version=25.1.8937393 \
          --sdk-version=33
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
