name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for better compatibility
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk autoconf automake libtool
        pip install buildozer cython==0.29.36
        
    - name: Initialize Buildozer environment
      run: |
        # Create minimal buildozer environment
        mkdir -p .buildozer/android
        buildozer android update
        # Ensure directories exist
        mkdir -p .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/python-for-android
        mkdir -p .buildozer/android/platform/python-for-android
        
    - name: Apply libffi patch
      run: |
        # Create directories if they don't exist
        mkdir -p ~/.buildozer/android/platform/python-for-android
        mkdir -p .buildozer/android/platform/python-for-android
        
        # Apply patches to both locations
        find ~/.buildozer -name 'configure.ac' -exec sed -i 's/AC_TRY_LINK/AC_LINK_IFELSE/g' {} + || true
        find ~/.buildozer -name 'configure' -exec sed -i 's/LT_SYS_SYMBOL_USCORE/_LT_SYS_SYMBOL_USCORE/g' {} + || true
        find .buildozer -name 'configure.ac' -exec sed -i 's/AC_TRY_LINK/AC_LINK_IFELSE/g' {} + || true
        find .buildozer -name 'configure' -exec sed -i 's/LT_SYS_SYMBOL_USCORE/_LT_SYS_SYMBOL_USCORE/g' {} + || true
        
    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/25.1.8937393" >> $GITHUB_ENV
        echo "USE_SDK_WRAPPER=1" >> $GITHUB_ENV
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
