name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk
        pip install buildozer cython==0.29.36
        
    - name: Setup Android SDK and accept licenses
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: 34.0.0
        platform-version: 33
        ndk-version: 25.1.8937393
        cmake-version: 3.22.1
        accept-android-licenses: true
        
    - name: Set environment variables for Buildozer
      run: |
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        
    - name: Initialize Buildozer
      run: |
        mkdir -p .buildozer/android/platform
        buildozer android -- version || true
        
    - name: Build APK
      run: |
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
