name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Use LTS version for compatibility
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev 
        sudo apt-get install -y libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt-get install -y python3-pip virtualenv

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer cython

    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec <<EOL
[app]
title = TikTok Report Bot
package.name = tiktokreportbot
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json
version = 1.0
requirements = python3,kivy,requests,urllib3,chardet,idna
android.permissions = INTERNET
orientation = portrait
android.arch = armeabi-v7a
p4a.branch = master
EOL

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-report-bot
        path: bin/*.apk
        retention-days: 3
