name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-distutils
        pip install buildozer cython==0.29.36 setuptools
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: 34.0.0
        platform-version: 33
        ndk-version: 25.1.8937393
        cmake-version: 3.22.1
        accept-android-licenses: true
        
    - name: Configure Buildozer
      run: |
        mkdir -p .buildozer/android/platform
        
        # Create buildozer.spec
        cat > buildozer.spec <<EOL
[app]

title = TikTokReportBot
package.name = tiktokreportbot
package.domain = org.tiktokreport
source.dir = .
source.include_exts = py
source.main = tiktok_report_bot.py
version = 1.0

# Requirements
requirements = python3, kivy==2.3.0, requests

# Android settings
android.minapi = 21
android.api = 33
orientation = portrait
android.permissions = INTERNET

# Use pre-installed SDK
android.sdk_path = $ANDROID_SDK_ROOT
android.ndk_path = $ANDROID_NDK_HOME
EOL
        
    - name: Build APK
      run: |
        # Verify Android tools
        echo "SDK path: $ANDROID_SDK_ROOT"
        echo "Build tools:"
        ls $ANDROID_SDK_ROOT/build-tools
        echo "AIDL path:"
        find $ANDROID_SDK_ROOT -name aidl
        
        # Build the APK
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
