name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # ✅ Java 17 (Needed for latest SDK tools)

      - name: Download and Install Android SDK Command-line Tools
        run: |
          mkdir -p ${HOME}/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ${HOME}/android-sdk/cmdline-tools/tmp
          mv ${HOME}/android-sdk/cmdline-tools/tmp/cmdline-tools ${HOME}/android-sdk/cmdline-tools/cmdline-tools
          rm -rf cmdline-tools.zip ${HOME}/android-sdk/cmdline-tools/tmp
          
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/cmdline-tools/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Accept Android SDK Licenses
        run: sdkmanager --licenses || true

      - name: Install Required SDK Packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Verify Installation
        run: adb --version
