name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-distutils
        pip install buildozer cython==0.29.36 setuptools
        
    - name: Initialize Buildozer (download SDK)
      run: |
        mkdir -p .buildozer/android/platform
        buildozer android -- version || true
        
    - name: Setup Android SDK licenses
      run: |
        # The SDK should have been downloaded by now in .buildozer/android/platform/android-sdk
        ANDROID_SDK_ROOT=".buildozer/android/platform/android-sdk"
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        # Also in the home directory to be safe
        mkdir -p ~/.android/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
        
    - name: Build APK
      run: |
        buildozer -v android debug \
          -- \
          --p4a-branch=master \
          --ndk-version=25.1.8937393 \
          --sdk-version=33
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tiktok-bot-apk
        path: bin/*.apk
